artifactory:
  admin: che
testapps:
  - name: testapp
    rootdir: apg-gradle-plugins-testsmodules/testapp/
    modules: testapp-bom testapp-parentpom testapp-module testapp-service
    pkg: testapp-pkg
  - name: testapp2
    rootdir: apg-gradle-plugins-testsmodules-2/testapp-2/
    modules: testapp-bom-2 testapp-parentpom-2 testapp-module-2 testapp-service-2
    pkg: testapp-pkg-2
  - name: testapp3
    rootdir: apg-gradle-plugins-testsmodules-3/testapp-3/
    modules: testapp-bom-3 test-parentpom-3 testapp-module-3 testapp-server-3 testapp-ui-runtime-3 testapp-jadas-appstarter-3 testapp-jadas-frameworkstarter-3
    pkg: testapp-ui-pkg-3 testapp-jadas-pkg-3

